var bup = document.createElement('button');
bup.style.position = 'absolute';
bup.style.left = '10%';
bup.style.bottom = '25%';
bup.style.width = '10%';
bup.style.height = '10%';
var bod = document.createElement('button');
bod.style.position = 'absolute';
bod.style.left = '10%';
bod.style.bottom = '10%';
bod.style.width = '10%';
bod.style.height = '10%';
var ble = document.createElement('button');
ble.style.position = 'absolute';
ble.style.left = '4%';
ble.style.bottom = '15%';
ble.style.width = '10%';
ble.style.height = '10%';
var bri = document.createElement('button');
bri.style.position = 'absolute';
bri.style.left = '25%';
bri.style.bottom = '15%';
bri.style.width = '10%';
bri.style.height = '10%';
document.body.appendChild(bri);
document.body.appendChild(ble);
document.body.appendChild(bod);
document.body.appendChild(bup);
