var bup = document.createElement('button');
bup.style.position = 'absolute';
bup.style.left = '19%';
bup.style.bottom = '35%';
bup.style.width = '15%';
bup.style.height = '13%';
bup.style.opacity = '0.5';
var bod = document.createElement('button');
bod.style.position = 'absolute';
bod.style.left = '19%';
bod.style.bottom = '6%';
bod.style.width = '15%';
bod.style.height = '13%';
bod.style.opacity = '0.5';
var ble = document.createElement('button');
ble.style.position = 'absolute';
ble.style.left = '5%';
ble.style.bottom = '20%';
ble.style.width = '15%';
ble.style.height = '13%';
ble.style.opacity = '0.5';
var bri = document.createElement('button');
bri.style.position = 'absolute';
bri.style.left = '35%';
bri.style.bottom = '20%';
bri.style.width = '15%';
bri.style.height = '13%';
bri.style.opacity = '0.5';
var rp = document.createElement('button');
rp.style.position = 'absolute';
rp.style.left = '1%';
rp.style.bottom = '90%';
rp.style.width = '10%';
rp.style.height = '10%';
//rplay.zIndex = '-1';
document.body.appendChild(rp);
document.body.appendChild(bri);
document.body.appendChild(ble);
document.body.appendChild(bod);
document.body.appendChild(bup);
