var wr = document.createElement('canvas');
wr.style.border = "1px";
var dv = document.createElement('div');
dv.style.textAlign = "center";
var btnp = document.createElement('button');
btnp.style.background = "green";
btnp.style.fontSize = "22px";
btnp.style.fontFamily = "Times New Roman";
document.body.appendChild(dv);
dv.appendChild(btnp);
